### ISSUE TITLE
Sharing on Discord won't resolve nor reject the promise

### ISSUE THREAD

**Issue by felippepuhle** [react-native-community/react-native-share#624]
### Steps to reproduce
1. Install this lib
2. Share something on Discord (with DM)

### Expected behaviour
Promise should be resolved or rejected

### Actual behaviour
Nothing happens after that

### Environment
- **React Native version**: 0.61.4
- **React Native platform + platform version**: iOS 13.1.3 (didn't try on Android, as our project is IOS only and I don't have one)

### react-native-share
**Version**: 2.0.0

**Comment by jgcmarins** [comment]
Thanks for the report
I guess this is already fixed on master, could you test it please?

**Comment by jgcmarins** [comment]
probably fixed here: https://github.com/react-native-community/react-native-share/pull/607

**Comment by felippepuhle** [comment]
Unfortunately it's not solved yet, even on a succeeded share we're getting a false `completed` [here](https://github.com/react-native-community/react-native-share/blob/master/ios/RNShare.m#L190).

Shouldn't we reject the promise in this case?

**Comment by jgcmarins** [comment]
got it
on a `succeeded` share we should resolve it

**Comment by felippepuhle** [comment]
Yup, but I don't know if it'll be possible as Discord is returning as an uncompleted share.

**Comment by mrtawil** [comment]
+1

**Comment by mrtawil** [comment]
+1
